version: '3'

services:
  app:
    image: shahroz43/nodeapplication:latest
    container_name: nodeapplication
    restart: always
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production