version: '3'

services:
  app:
    image: shahroz43/nodeapplication:latest
    container_name: nodeapplication
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production